brew_taps:
  - ublue-os/tap
  - Valkyrie00/homebrew-bbrew

brew_packages:
  - act
  - atuin
  - awscli
  - bat
  - bat-extras
  - bbrew
  - bitwarden-cli
  - cosign
  - eza
  - fastfetch
  - fzf
  - go
  - jq
  - jump
  - nethogs
  - nvtop
  - pstree
  - pyenv
  - pyenv-virtualenv
  - ripgrep
  - rsync
  - skopeo
  - tldr
  - tmux
  - wget
  - xsel
  - yq
  
brew_casks:
  - framework-tool

